vim.g.netrw_banner          = 0
vim.g.netrw_list_cmd        = 'ls -Fa'
vim.g.netrw_liststyle       = 0
vim.g.netrw_mkdir_cmd       = 'mkdir'
vim.g.netrw_rename_cmd      = 'mv'
vim.g.netrw_rm_cmd          = 'rm'
vim.g.netrw_rmdir_cmd		= 'rmdir'
vim.g.netrw_rmf_cmd			= 'rm -f'
vim.g.netrw_localcopydircmd = 'cp -r'
